import Head from 'next/head'
import { useEffect, useState } from 'react'
import axios from 'axios'
import styles from '@/styles/Home.module.css'
import Header from '@/components/organisms/Header/Header'
import Footer from '@/components/organisms/Footer/Footer'
import Skycapers from '@/components/organisms/Skycapers/Skycapers'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Link from 'next/link'
import Gallery from '@/components/organisms/Gallery/Gallery'

export default function Home({ }) {
  const [skycapers, setSkycapers] = useState(null)
  const [galleries, setGallery] = useState(null)
  const fetchData = async () => {
    try {
      const response = await axios.get(
        "https://656599ffeb8bb4b70ef1ebb4.mockapi.io/skyscrapers",
      );
      const filteredSkycapers = response.data.sort((a, b) => (a.building_height > b.building_height ? -1 : 1));
      const limitSkycapers = filteredSkycapers.slice(0, 3)
      setSkycapers(limitSkycapers);

      const limitedGalleries = response.data.slice(0, 3);
      setGallery(limitedGalleries);
    } catch (err) {
      console.log(err);
    }
  }
  useEffect(() => {
    fetchData()
  }, [])

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/89937a7b06.js" crossorigin="anonymous"></script>
      </Head>
      <Header />
      <main className={`${styles.main} ${inter.className}`}>

        <div className={styles.topThreeSkycapers}>
          <div className={styles.heading}>
            <h2>TOP 3</h2>
          </div>
          <Skycapers skycapers={skycapers} />
          <Link href="/skycapers" className={styles.btn}>see more</Link>
        </div>
        <div className={styles.top_three_gallery_home}>
          <div className={styles.heading}>
            <h2>Top 3</h2>
          </div>
          <Gallery galleries={galleries} />
          <div>
            <Link href="/gallery" className={styles.btn}>see more</Link>
          </div>
        </div>
        <div className={styles.give_us_call}>
          <div className={styles.heading}>
            <h2>Give us call</h2>
          </div>
          <div>
            <Link href="/contacts" className={styles.btn}>see more</Link>
          </div>
        </div>

      </main>
      <Footer />
    </>
  )
}
